### ISSUE TITLE
Error. Unauthorized Access

### ISSUE THREAD

**Issue by Kammi61871** [marvingrieger/ioBroker.pallazza#13]
pallazza.1 | 2020-04-13 07:07:06.747 | error | (24505) POST response: [object Object] [RESPONSE];  <head><title>HIS WEB  Server</title></head><body><h2>HTTP 1.0 401  Error. Unauthorized Access</h2>You are not authorized to access  this server.</body>
-- | -- | -- | --
pallazza.1 | 2020-04-13 07:07:06.742 | error | (24505) stateChange (command): pallazza.1.device.prg  {"val":false,"ack":false,"ts":1586754426277,"q":0,"from":"system.adapter.iot.0","user":"system.user.admin","lc":1586754426277}  was not successful

Since some days I observe in the log these entries.

build 0.2.4

the oven retuns no commands what i say to alexa

HSP 2.17 PREMIUM (V5.13)

**Comment by marvingrieger** [comment]
Hey, it seems like an incorrect token is calculated.

Doesn't it work at all, or does it fail sometimes?
I.e., are you able to start the device / change its temperature at all?

If it's working sometimes, I would assume, that the nonce is out of sync.
To verify this, you can check the following:

- Visit the website of your device: http://**IP_OF_YOUR_DEVICE**/status.cgi
- You should see some text. Within the text you will find the entry **nonce : NONCE_VALUE**
- In the object model of ioBroker you'll find the value in the object tree under **pallaza.0 / device / meta / nonce**

Do both nonce values match?

**Comment by Kammi61871** [comment]
Sry for late response, no cgi say

nonce | "WTwprqDi0sXQ6FES"

iobroker

GjOkt6KwmDwjslxg

today i had a firmware update but nothing has changed for me

`{"meta":{"sw_version":"V5.13","hw_version":"KS01","bootl_version":"V1.2","wifi_sw_version":"V2.2.1","wifi_bootl_version":"-","sn":"1316598","typ":"HSP-1\/2","language":"de","nonce":"WTwprqDi0sXQ6FES","wlan_features":["l", "hl", "wp"]},"prg":false,"wprg":false,"mode":"off","sp_temp":24,"is_temp":24.02,"ht_char":4,`

**Comment by marvingrieger** [comment]
Ok, so it seems like the adapter is out of sync. I would assume, that it does not update any values at all - can you please check? For example, is the temperature field ("is_temp") updated?

I would suggest that you reinstall the adapter. If this does not solve your problem, can you please set the log level of the adapter to "debug" and post the information?

**Comment by marvingrieger** [comment]
This ticket seems to be stalled. Please reopen, if the problem still exists.
