### ISSUE TITLE
Verbindung mit HSP 6 Pelletto IV 434.08 klappt nur kurz und bricht ab

### ISSUE THREAD

**Issue by Armin46** [marvingrieger/ioBroker.pallazza#15]
Hallo,

leider bricht die Verbindung zum Ofen gleich wieder ab es werden zwar kurz die Objekte aktuallisiert aber dann kommen direkt 3 Fehlermeldungen und der Adapter hängt.

Gibt es hier ein Lösung?

Anbei der Auzug aus dem Log.

`

pallazza.0 | 2020-07-18 14:17:06.058 | error | (13497) Some critical error occurred (see log). Disabling the adapter
-- | -- | -- | --
pallazza.0 | 2020-07-18 14:17:06.054 | warn | (13497) State device.meta.itemid does not exist. Please contact the developer.
pallazza.0 | 2020-07-18 14:17:06.044 | error | (13497) Hardware / Software version (KS01_V7.08) is not supported by this adapter!

`

**Comment by marvingrieger** [comment]
Hallo,

ich habe den Adapter konservativ eingestellt, in dem Sinne, dass er sich bei einer unbekannten Hardware- / Software-Kombination beendet. Dies vor dem Hintergrund, dass es hier schließlich um einen Ofen geht 😊

Ich habe den Adapter für diese Version in einem Branch freigeschaltet:

https://github.com/marvingrieger/ioBroker.pallazza/tarball/KS01_V7.08

Bitte einmal über die URL installieren und testen ...
- ... ob der Adapter wie erwartet funktioniert
- ... ob im Log Hinweise auf fehlende Zustände auftauchen (Meldung: "State XYZ does not exist")?

Sofern alles in Ordnung ist, merge ich das ganze in den master.
Was für ein Ofen wird hier verwendet?

Beste Grüße

**Comment by Armin46** [comment]
Hallo,

ja das macht schon Sinn den Adapater so einzustellen.

Mit der Version funktioniert der Adapter jetzt ohne Fehlermeldungen im Log.

Leider ist nicht aktuell nicht erkennbar für was der Wert "itemid" steht, er hat aktuellen den Wert "?"
Wenns in die Heizperiode geht schaue ich mir das nochmal an und gebe ich Bescheid falls was Erkennbar ist.

Im Log tauchen keine fehlenden Zustände mehr auf.

Es wird der Ofen HSP 6 Pelletto IV 434.08 verwendet.


Vielen Dank für die schnelle behebung und den Klasse Adapter.

Grüße Armin
