### ISSUE TITLE
Hardware / Software version (KS01_V5.13)

### ISSUE THREAD

**Issue by Kammi61871** [marvingrieger/ioBroker.pallazza#8]
|   |   |  
-- | -- | -- | --
pallazza.0 | 2019-08-21 18:32:25.565 | error | Some critical error occurred (see log). Disabling the adapter
pallazza.0 | 2019-08-21 18:32:25.543 | error | Hardware / Software version (KS01_V5.13)is not supported by this adapter!

any chance to get to work with it ?
Haas+Sohn HSP 2.17 PREMIUM

**Comment by marvingrieger** [comment]
Hey, I enabled your device in the following branch:

https://github.com/marvingrieger/ioBroker.pallazza/tree/KS01_V5.13

However, I am not able to test it.
If it works, please let me know so I can enable it globally.

**Comment by Kammi61871** [comment]
Hey, i get this error

`

host.raspberrypi | 2019-10-04 22:34:36.385 | error | Cannot  write files:  /opt/iobroker/iobroker-data/files/pallazza.admin/_data.json: ENOENT: no  such file or directory, open  '/opt/iobroker/iobroker-data/files/pallazza.admin/_data.json'
-- | -- | -- | --
host.raspberrypi | 2019-10-04 22:31:11.447 | info | Update repository "default" under "http://download.iobroker.net/sources-dist.json"
iobroker | 2019-10-04 22:31:11.291 | info | exit 0
iobroker | 2019-10-04 22:31:11.168 | info | upload [0] pallazza.admin /opt/iobroker/node_modules/iobroker.pallazza/admin/haassohn.png haassohn.png image/png
iobroker | 2019-10-04 22:31:11.108 | info | upload [1] pallazza.admin  /opt/iobroker/node_modules/iobroker.pallazza/admin/i18n/de/translations.json  i18n/de/translations.json application/json
iobroker | 2019-10-04 22:31:11.045 | info | upload [2] pallazza.admin  /opt/iobroker/node_modules/iobroker.pallazza/admin/i18n/en/translations.json  i18n/en/translations.json application/json
iobroker | 2019-10-04 22:31:10.976 | info | upload [3] pallazza.admin /opt/iobroker/node_modules/iobroker.pallazza/admin/index.html index.html text/html
iobroker | 2019-10-04 22:31:10.913 | info | upload [4] pallazza.admin /opt/iobroker/node_modules/iobroker.pallazza/admin/index_m.html index_m.html text/html
iobroker | 2019-10-04 22:31:10.581 | info | upload [5] pallazza.admin /opt/iobroker/node_modules/iobroker.pallazza/admin/words.js words.js application/javascript
iobroker | 2019-10-04 22:31:10.555 | info | got /opt/iobroker/node_modules/iobroker.pallazza/admin
iobroker | 2019-10-04 22:31:10.387 | info | found 75 vulnerabilities (43 low, 32 high)  run `npm audit fix` to fix them, or `npm audit` for details
iobroker | 2019-10-04 22:31:10.377 | info | + iobroker.pallazza@0.2.1added 5 packages from 5 contributors and audited 16043 packages in 50.027s
iobroker | 2019-10-04 22:31:10.353 | info |  
iobroker | 2019-10-04 22:31:10.351 | info | WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for  osx-temperature-sensor@1.0.4: wanted {"os":"darwin","arch":"any"}  (current: {"os":"linux","arch":"arm"})
iobroker | 2019-10-04 22:31:10.349 | info | WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.4 (node_modules/osx-temperature-sensor):npm

`

**Comment by marvingrieger** [comment]
Hey, I just installed the adapter from your fork ... works fine on my side.

The message might indicate a general problem with your installation. Maybe try a clean install?

**Comment by Kammi61871** [comment]
Ok it works fine now thanks for your work

**Comment by marvingrieger** [comment]
Nice. Please let me know if the adapter works as expected. In particular:

- Do you see an error like "State X does not exist" in the log?
- Are you able to change the temperature of the oven?

If everything works well, I'll add your hardware / software combination to the list of supported devices.

**Comment by Kammi61871** [comment]
Hi, no errors im able to change the temperature and turn the oven on/off.

**Comment by marvingrieger** [comment]
Nice, I added the support in the master.

Let me know if you are missing some functionality. In theory, it should be possible to at least provide any functionality which the regular Haas+Sohn app provides.
